name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'zensical.toml'

  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'main'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install zensical

      - run: zensical build --clean

      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Clear files
        working-directory: gh-pages
        run: find . ! -name 'index.yaml' ! -path './index.yaml' ! -path '.' -exec rm -rf {} +

      - name: Deploy to gh-pages
        working-directory: main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          cp -r site/* "$GITHUB_WORKSPACE/gh-pages"
          
          # Commit and push
          git add .
          git commit -m "Deploy from main" || echo "No changes to commit"
          git push origin gh-pages --force
